# =========================
# TMUX CONFIG
# =========================
# set -g mouse on
set -g history-limit 100000
setw -g mode-keys vi
set -g set-clipboard on
set -g base-index 1
setw -g pane-base-index 1

source-file ~/.config/tmux/conf.d/tmux-keys.conf
source-file ~/.config/tmux/conf.d/tmux-plugins.conf
source-file ~/.config/tmux/conf.d/tmux-statusbar.conf
