# =========================
# TMUX CONFIG
# =========================

# BASE
set -g pane-border-lines heavy
# set -g mouse on
set -g history-limit 100000
setw -g mode-keys vi
set -g set-clipboard on
set -g base-index 1
setw -g pane-base-index 1

# SPLITS PANES (Alt + vs)
bind -n M-v split-window -h
bind -n M-s split-window -v

# NAVIGATION (Alt + hjkl)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# CYCLE PANES (Alt + o;)
bind -n M-o select-pane -t :.+
bind -n M-\; last-pane

# MOVE PANES (Alt + Shift + hjkl)
bind -n M-H swap-pane -t "{left-of}"
bind -n M-J swap-pane -t "{down-of}"
bind -n M-K swap-pane -t "{up-of}"
bind -n M-L swap-pane -t "{right-of}"

# RESIZE PANES (Alt + Ctrl + hjkl)
bind -n M-C-h resize-pane -L 5
bind -n M-C-j resize-pane -D 2
bind -n M-C-k resize-pane -U 2
bind -n M-C-l resize-pane -R 5

# CYCLE LAYOUTS (Alt + space)
bind -n M-Space next-layout

# WINDOWS (Alt + c/enter)
bind -n M-c new-window
bind -n M-Enter new-window

# WINDOW NAVIGATION (Alt + 123456789/n/p/m)
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-n next-window
bind -n M-p previous-window
bind -n M-m last-window

# WINDOW MANAGEMENT (Alt +, / Alt + Shift X)
bind -n M-, command-prompt -I "#W" "rename-window '%%'"
bind -n M-X kill-window

# SESSION / CLIENT DETACH (Alt + d)
bind -n M-d detach-client

# SESSION / WINDOW TREE (Alt + w)
bind -n M-w choose-tree -Zw

# SHOW PANE NUMBERS (Alt + q)
bind -n M-q display-panes

# PANE <-> WINDOW (Alt + b/B)
bind -n M-b break-pane
bind -m M-B join-pane

# CLOCK (Alt + t)
bind -n M-t clock-mode

# RELOAD CONFIG (Alt + r)
bind -n M-r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

# KILL PANE (Alt + x)
bind -n M-x kill-pane

# COPY MODE (Alt + [ )
bind -n M-[ copy-mode

# ZOOM MODE (Alt + z)
bind -n M-z resize-pane -Z

# MOUSE
bind -n MouseDragEnd1Pane copy-mode
